In [1]:
import torch

In [2]:
example_tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)

In [3]:
example_tensor.shape

torch.Size([3, 2, 2])

In [4]:
example_tensor.device

device(type='cpu')

In [6]:
example_tensor.numel()


12

In [7]:
example_tensor[1]

tensor([[5., 6.],
        [7., 8.]])

In [8]:
example_tensor[1,1,0] == 7

tensor(True)

In [9]:
example_tensor[1,1,0].item()

7.0

In [10]:
torch.ones_like(example_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [11]:
torch.rand_like(example_tensor)

tensor([[[0.3841, 0.5310],
         [0.3345, 0.1889]],

        [[0.7409, 0.4565],
         [0.9268, 0.6663]],

        [[0.5518, 0.3854],
         [0.1640, 0.8569]]])

In [12]:
torch.randn(2,2, device ='cuda')

tensor([[ 0.6758, -0.1975],
        [-1.5032, -1.9045]], device='cuda:0')

In [13]:
(example_tensor -5)*2


tensor([[[ -8.,  -6.],
         [ -4.,  -2.]],

        [[  0.,   2.],
         [  4.,   6.]],

        [[  8., -10.],
         [ -8.,  -6.]]])

In [15]:
example_tensor.mean()
example_tensor.std()

tensor(2.9848)

In [16]:
import torch.nn as nn

In [18]:
linear = nn.Linear(10,2)
example_input = torch.randn(3,10)
example_output = linear(example_input)
example_output

tensor([[-0.2844, -0.1289],
        [ 0.0042,  0.6716],
        [-0.4359, -0.2431]], grad_fn=<AddmmBackward0>)

In [19]:
relu = nn.ReLU()
relu_output =relu(example_output)
relu_output

tensor([[0.0000, 0.0000],
        [0.0042, 0.6716],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)

In [20]:
batchnorm = nn.BatchNorm1d(2)
batchnorm_output = batchnorm(relu_output)
batchnorm_output

tensor([[-0.3755, -0.7071],
        [ 0.7510,  1.4141],
        [-0.3755, -0.7071]], grad_fn=<NativeBatchNormBackward0>)

In [22]:
mlp_layer = nn.Sequential(
    nn.Linear(5,2),
    nn.BatchNorm1d(2),
    nn.ReLU()
    )
test_example = torch.randn(5,5) +1
print("input : ")
print(test_example)
print('output')
print(mlp_layer(test_example))

input : 
tensor([[ 1.1082,  0.3977,  1.7381,  0.4026, -0.3911],
        [ 1.5725,  0.6897,  0.9161, -0.3329, -0.4512],
        [ 1.8870, -0.1650,  2.4299,  0.8282,  1.0473],
        [-0.4282,  1.3352, -0.4037, -0.3404, -0.1761],
        [ 0.7357,  1.3047,  0.5313,  1.2089,  2.0806]])
output
tensor([[0.5706, 0.0000],
        [0.6896, 0.5540],
        [0.0000, 0.0000],
        [1.1271, 1.0316],
        [0.0000, 0.5194]], grad_fn=<ReluBackward0>)


In [23]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layer.parameters(), lr = 1e-1)

In [ ]:
#Training Loop


In [24]:
import torch
from torch import nn

In [33]:
class LogisticRegression(nn.Module):
    def __init__(self, i):
        super().__init__()
        self.log_reg = nn.Sequential(
            nn.Linear(i,1),
            nn.Sigmoid()
        )

    def forward(self,x):
            return self.log_reg(x)

In [51]:
model = LogisticRegression(16)
criterion = nn.BCELoss()  # cost function
optimizer = torch.optim.SGD(model.parameters(), lr =0.01)
n_epochs =3
for t in range(n_epochs):
    y_pred = model(x)
    loss = criterion(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


torch.Size([1])
torch.Size([1])
torch.Size([1])
torch.Size([1])
torch.Size([1])
torch.Size([1])


In [28]:
x = torch.randn(16)
x

tensor([-0.1253,  0.9922,  1.2680, -0.9265, -1.3414,  0.1978,  0.4858, -0.4285,
        -1.0308, -0.2667,  1.2663,  0.7057, -0.9488, -0.9598,  0.9339, -1.9484])

In [50]:
# y = torch.tensor([torch.dot(x,x)])
# y.size()
y = torch.tensor([1.0])